# Generated by Django 4.2.7 on 2023-11-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_random_quote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='random',
        ),
    ]
